name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: pulumi up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: eu-west-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          cloud-url: ${{ vars.PULUMI_CLOUD_URL }}
          stack-name: ${{ github.event.number > 0 && format('dev-pr-{0}', github.event.number) || 'dev' }}
          comment-on-pr: true
          upsert: true
          secrets-provider: ${{ vars.PULUMI_SECRETS_PROVIDER }}
